# Generated by Django 5.0.6 on 2024-06-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=200, unique=True)),
                ('user', models.CharField(max_length=200, unique=True)),
                ('distance', models.FloatField()),
                ('duration', models.FloatField()),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('calories_burnt', models.IntegerField()),
            ],
            options={
                'ordering': ['registered_on'],
            },
        ),
    ]
