# Generated by Django 5.0.6 on 2024-06-17 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_activity_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='calories_burnt',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='calories_intake',
        ),
    ]
