# Generated by Django 5.0.6 on 2024-06-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_profile_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='weight_target',
            field=models.FloatField(default=75),
            preserve_default=False,
        ),
    ]
