# Generated by Django 5.0.6 on 2024-06-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_profile_weight_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(default='1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight_target',
            field=models.FloatField(default='1'),
        ),
    ]
