# Generated by Django 5.0.6 on 2024-06-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_profile_birthdate_alter_profile_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(default='1'),
        ),
    ]
