# Generated by Django 5.0.6 on 2024-06-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_profile_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='nutrition_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight_target',
            field=models.FloatField(),
        ),
    ]
