# Generated by Django 5.0.6 on 2024-07-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_activity_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='calories_burnt',
            field=models.IntegerField(),
        ),
    ]
