# Generated by Django 5.0.6 on 2024-07-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='calories_intake',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
