# Generated by Django 5.0.6 on 2024-07-07 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_nutrition_food_item_alter_nutrition_portion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='food_item',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only alphabetical characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='portion',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2999), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)]),
        ),
    ]
