# Generated by Django 5.0.6 on 2024-07-07 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_nutrition_food_item_alter_nutrition_portion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(default='1990-09-07'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(default=180, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
