# Generated by Django 5.0.6 on 2024-07-09 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_profile_birthdate_alter_profile_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only alphabetical characters                                        are allowed.')]),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='food_item',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only alphabetical characters                                        are allowed.')]),
        ),
    ]
